In [1]:
import numpy as np 
import pandas as pd

import warnings
warnings.filterwarnings('ignore')

In [3]:
df=pd.read_csv("loan_prediction.csv")

In [4]:
df

Loan_ID  Gender Married Dependents     Education Self_Employed  \
0    LP001002    Male      No          0      Graduate            No   
1    LP001003    Male     Yes          1      Graduate            No   
2    LP001005    Male     Yes          0      Graduate           Yes   
3    LP001006    Male     Yes          0  Not Graduate            No   
4    LP001008    Male      No          0      Graduate            No   
..        ...     ...     ...        ...           ...           ...   
609  LP002978  Female      No          0      Graduate            No   
610  LP002979    Male     Yes         3+      Graduate            No   
611  LP002983    Male     Yes          1      Graduate            No   
612  LP002984    Male     Yes          2      Graduate            No   
613  LP002990  Female      No          0      Graduate           Yes   

     ApplicantIncome  CoapplicantIncome  LoanAmount  Loan_Amount_Term  \
0               5849                0.0         NaN             360.0   
1               4583             1508.0       128.0             360.0   
2               3000                0.0        66.0             360.0   
3               2583             2358.0       120.0             360.0   
4               6000                0.0       141.0             360.0   
..               ...                ...         ...               ...   
609             2900                0.0        71.0             360.0   
610             4106                0.0        40.0             180.0   
611             8072              240.0       253.0             360.0   
612             7583                0.0       187.0             360.0   
613             4583                0.0       133.0             360.0   

     Credit_History Property_Area Loan_Status  
0               1.0         Urban           Y  
1               1.0         Rural           N  
2               1.0         Urban           Y  
3               1.0         Urban           Y  
4               1.0         Urban           Y  
..              ...           ...         ...  
609             1.0         Rural           Y  
610             1.0         Rural           Y  
611             1.0         Urban           Y  
612             1.0         Urban           Y  
613             0.0     Semiurban           N  

[614 rows x 13 columns]

In [5]:
df.shape


(614, 13)

# Handle the Missing values

In [6]:
df.isnull().sum()


Loan_ID               0
Gender               13
Married               3
Dependents           15
Education             0
Self_Employed        32
ApplicantIncome       0
CoapplicantIncome     0
LoanAmount           22
Loan_Amount_Term     14
Credit_History       50
Property_Area         0
Loan_Status           0
dtype: int64

# Treating the Null Value

In [7]:
numerical_features = df.select_dtypes(include = [np.number]).columns
categorical_features = df.select_dtypes(include = [np.object]).columns

In [8]:
numerical_features

Index(['ApplicantIncome', 'CoapplicantIncome', 'LoanAmount',
       'Loan_Amount_Term', 'Credit_History'],
      dtype='object')

In [9]:
categorical_features

Index(['Loan_ID', 'Gender', 'Married', 'Dependents', 'Education',
       'Self_Employed', 'Property_Area', 'Loan_Status'],
      dtype='object')

In [11]:
df['Gender'] = df['Gender'].fillna(df['Gender'].mode()[0])
df['Married'] = df['Married'].fillna(df['Married'].mode()[0])
#replace + with non value 
df['Dependents'] = df['Dependents'].str.replace('+','')
df['Dependents'] = df['Dependents'].fillna(df['Dependents'].mode()[0])
df['LoanAmount'] = df['LoanAmount'].fillna(df['LoanAmount'].mode()[0])
df['Self_Employed'] = df['Self_Employed'].fillna(df['Self_Employed'].mode()[0])
df['Loan_Amount_Term'] = df['Loan_Amount_Term'].fillna(df['Loan_Amount_Term'].mode()[0])
df['Credit_History'] = df['Credit_History'].fillna(df['Credit_History'].mode()[0])


In [12]:
df.isnull().sum()


Loan_ID              0
Gender               0
Married              0
Dependents           0
Education            0
Self_Employed        0
ApplicantIncome      0
CoapplicantIncome    0
LoanAmount           0
Loan_Amount_Term     0
Credit_History       0
Property_Area        0
Loan_Status          0
dtype: int64

# Handling Categorical Values

In [13]:
df.select_dtypes(include='object').columns

Index(['Loan_ID', 'Gender', 'Married', 'Dependents', 'Education',
       'Self_Employed', 'Property_Area', 'Loan_Status'],
      dtype='object')

In [14]:
df['Gender'].unique()

array(['Male', 'Female'], dtype=object)

In [15]:
df['Gender'].replace({'Male':1,'Female':0},inplace=True)

In [16]:
df['Married'].unique()

array(['No', 'Yes'], dtype=object)

In [17]:
df['Married'].replace({'Yes':1,'No':0},inplace=True)

In [18]:
df['Dependents'].unique()

array(['0', '1', '2', '3'], dtype=object)

In [19]:
df['Dependents'].replace({'0':0,'1':1,'2':2,'3':3},inplace=True)

In [20]:
df['Self_Employed'].unique()

array(['No', 'Yes'], dtype=object)

In [21]:
df['Self_Employed'].replace({'Yes':1,'No':0},inplace=True)

In [22]:
df['Property_Area'].unique()

array(['Urban', 'Rural', 'Semiurban'], dtype=object)

In [24]:
df['Property_Area'].replace({'Urban':2,'Rural':0,'Semiurban':1},inplace=True)


In [25]:
df['Loan_Status'].unique()

array(['Y', 'N'], dtype=object)

In [26]:
df['Loan_Status'].replace({'Y':1,'N':0},inplace=True)

In [27]:
df['Education'].unique()

array(['Graduate', 'Not Graduate'], dtype=object)

In [28]:
df['Education'].replace({'Graduate':1,'Not Graduate':0},inplace=True)

In [29]:
df['CoapplicantIncome']=df['CoapplicantIncome'].astype("int64")
df['LoanAmount']=df['LoanAmount'].astype("int64")
df['Loan_Amount_Term']=df['Loan_Amount_Term'].astype("int64")
df['Credit_History']=df['Credit_History'].astype("int64")

In [30]:
# dummy columns are created for the categories in Loan_ID
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
df['Loan_ID'] = le.fit_transform(df.Loan_ID)

In [31]:
df.head()


Loan_ID  Gender  Married  Dependents  Education  Self_Employed  \
0        0       1        0           0          1              0   
1        1       1        1           1          1              0   
2        2       1        1           0          1              1   
3        3       1        1           0          0              0   
4        4       1        0           0          1              0   

   ApplicantIncome  CoapplicantIncome  LoanAmount  Loan_Amount_Term  \
0             5849                  0         120               360   
1             4583               1508         128               360   
2             3000                  0          66               360   
3             2583               2358         120               360   
4             6000                  0         141               360   

   Credit_History  Property_Area  Loan_Status  
0               1              2            1  
1               1              0            0  
2               1              2            1  
3               1              2            1  
4               1              2            1

# Balancing The Dataset

In [32]:
from imblearn.combine import SMOTETomek

In [33]:
smote = SMOTETomek(0.90)

In [34]:
#dividing the dataset into dependent and independent y and x respectively

y = df['Loan_Status']
x = df.drop(columns=['Loan_Status'],axis=1)

In [35]:
#creating the new x and y for balance data
x_bal,y_bal = smote.fit_resample(x,y)

In [36]:
#printing the value before and after balancing 
print(y.value_counts())
print(y_bal.value_counts())


1    422
0    192
Name: Loan_Status, dtype: int64
1    370
0    327
Name: Loan_Status, dtype: int64



# Scaling The Data

In [37]:
from sklearn.preprocessing import StandardScaler


In [38]:
sc = StandardScaler()
x_bal = sc.fit_transform(x_bal)

In [39]:
x_bal = pd.DataFrame(x_bal)

In [40]:
x_bal.head()




0         1         2         3         4         5         6   \
0 -1.762937  0.514755 -1.174240 -0.708088  0.627694 -0.334130  0.090721   
1 -1.757097  0.514755  0.851615  0.344230  0.627694 -0.334130 -0.136207   
2 -1.751258  0.514755  0.851615 -0.708088  0.627694  2.992849 -0.419958   
3 -1.745418  0.514755  0.851615 -0.708088 -1.593132 -0.334130 -0.494705   
4 -1.739578  0.514755 -1.174240 -0.708088  0.627694 -0.334130  0.117788   

         7         8         9         10        11  
0 -0.493612 -0.310718  0.275633  0.601106  1.334267  
1 -0.014487 -0.210344  0.275633  0.601106 -1.241866  
2 -0.493612 -0.988247  0.275633  0.601106  1.334267  
3  0.255577 -0.310718  0.275633  0.601106  1.334267  
4 -0.493612 -0.047235  0.275633  0.601106  1.334267

# Splitting Data Into Train And Test

In [41]:
# splitting the data into training and testing set

from sklearn.model_selection import train_test_split

In [42]:
x_train, x_test, y_train, y_test = train_test_split(x_bal, y_bal, test_size = 0.33, random_state = 42)


In [44]:
print(x_train.shape)
print(y_train.shape)
print(x_test.shape)
print(y_test.shape)

(466, 12)
(466,)
(231, 12)
(231,)


In [45]:
x_train.to_csv('train.csv',encoding='utf-8',index=False)
x_test.to_csv('test.csv',encoding='utf-8',index=False)

# COMPARE THE MODEL

## Decision Tree Model

In [46]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report,f1_score


In [47]:
def decisionTreeClassifier(x_train, x_test, y_train, y_test):
    dt = DecisionTreeClassifier() 
    dt.fit(x_train,y_train)
    yPred = dt.predict(x_test)
    print("****DecisionTreeClassifier****") 
    print("Confusion matrix")
    print(confusion_matrix(y_test ,yPred) ) 
    print("Classification report")
    print(classification_report (y_test, yPred))
    y_pred=dt.predict(x_test)
    y_pred1=dt.predict(x_train)
    print('Testing accuracy: ',accuracy_score(y_test,y_pred))
    print('Training accuracy: ',accuracy_score(y_train,y_pred1))

In [48]:
decisionTreeClassifier(x_train, x_test, y_train, y_test)

****DecisionTreeClassifier****
Confusion matrix
[[66 38]
 [31 96]]
Classification report
              precision    recall  f1-score   support

           0       0.68      0.63      0.66       104
           1       0.72      0.76      0.74       127

    accuracy                           0.70       231
   macro avg       0.70      0.70      0.70       231
weighted avg       0.70      0.70      0.70       231

Testing accuracy:  0.7012987012987013
Training accuracy:  1.0


# Random Forest Model

In [49]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report,f1_score


In [50]:
def randomForestClassifier(x_train, x_test, y_train, y_test):
    rf = RandomForestClassifier() 
    rf.fit(x_train,y_train)
    yPred = rf.predict(x_test)
    print("****RandomForestClassifier****") 
    print("Confusion matrix")
    print(confusion_matrix(y_test ,yPred) ) 
    print("Classification report")
    print(classification_report (y_test, yPred))
    y_pred=rf.predict(x_test)
    y_pred1=rf.predict(x_train)
    print('Testing accuracy: ',accuracy_score(y_test,y_pred))
    print('Training accuracy: ',accuracy_score(y_train,y_pred1))

In [51]:
randomForestClassifier(x_train, x_test, y_train, y_test)

****RandomForestClassifier****
Confusion matrix
[[ 73  31]
 [ 13 114]]
Classification report
              precision    recall  f1-score   support

           0       0.85      0.70      0.77       104
           1       0.79      0.90      0.84       127

    accuracy                           0.81       231
   macro avg       0.82      0.80      0.80       231
weighted avg       0.81      0.81      0.81       231

Testing accuracy:  0.8095238095238095
Training accuracy:  1.0



# KNN Model

In [52]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report,f1_score


In [53]:
def kneighborsClassifier(x_train, x_test, y_train, y_test):
    knn = KNeighborsClassifier() 
    knn.fit(x_train,y_train)
    yPred = knn.predict(x_test)
    print("****KNeighborsClassifier****") 
    print("Confusion matrix")
    print(confusion_matrix(y_test ,yPred) ) 
    print("Classification report")
    print(classification_report (y_test, yPred))
    y_pred=knn.predict(x_test)
    y_pred1=knn.predict(x_train)
    print('Testing accuracy: ',accuracy_score(y_test,y_pred))
    print('Training accuracy: ',accuracy_score(y_train,y_pred1))

In [54]:
kneighborsClassifier(x_train, x_test, y_train, y_test)


****KNeighborsClassifier****
Confusion matrix
[[ 65  39]
 [ 16 111]]
Classification report
              precision    recall  f1-score   support

           0       0.80      0.62      0.70       104
           1       0.74      0.87      0.80       127

    accuracy                           0.76       231
   macro avg       0.77      0.75      0.75       231
weighted avg       0.77      0.76      0.76       231

Testing accuracy:  0.7619047619047619
Training accuracy:  0.8605150214592274



# Xgboost Model

In [56]:
from sklearn.ensemble import  GradientBoostingClassifier
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report,f1_score


In [58]:
def xgboost(x_train, x_test, y_train, y_test):
    xg = GradientBoostingClassifier() 
    xg.fit(x_train,y_train)
    yPred = xg.predict(x_test)
    print("****Gradient BoostingClassifier****") 
    print("Confusion matrix")
    print(confusion_matrix(y_test ,yPred) ) 
    print("Classification report")
    print(classification_report (y_test, yPred))
    y_pred=xg.predict(x_test)
    y_pred1=xg.predict(x_train)
    print('Testing accuracy: ',accuracy_score(y_test,y_pred))
    print('Training accuracy: ',accuracy_score(y_train,y_pred1))

In [59]:
xgboost(x_train, x_test, y_train, y_test)


****Gradient BoostingClassifier****
Confusion matrix
[[ 68  36]
 [ 14 113]]
Classification report
              precision    recall  f1-score   support

           0       0.83      0.65      0.73       104
           1       0.76      0.89      0.82       127

    accuracy                           0.78       231
   macro avg       0.79      0.77      0.78       231
weighted avg       0.79      0.78      0.78       231

Testing accuracy:  0.7835497835497836
Training accuracy:  0.9356223175965666


 
# Evaluating Performance Of The Model And Saving The Model

In [60]:
from sklearn.model_selection import cross_val_score

In [61]:
xg = GradientBoostingClassifier()

In [62]:
xg.fit(x_train,y_train)

GradientBoostingClassifier()

In [63]:
yPred = xg.predict(x_test)

In [64]:
f1_score(yPred,y_test, average='weighted')

0.7786499879992657

In [65]:
cv = cross_val_score(xg,x,y,cv=5)

In [66]:
np.mean(cv)

0.7149540183926429

In [67]:
import pickle
#saviung the model by using pickle function
pickle.dump(xg, open('model.pkl','wb'))
pickle.dump(sc,open("scalar.pkl","wb"))

In [68]:
loaded_xg = pickle.load(open('model.pkl','rb'))
loaded_xg.predict(x_test)

array([1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0,
       0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0,
       0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 1,
       1, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1,
       0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0,
       1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0,
       0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1,
       1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1, 1,
       1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0,
       1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1])