# **Compare The Model**

**IMPORTING THE PACKAGE**

In [ ]:
import numpy as np 
import pandas as pd

import warnings
warnings.filterwarnings('ignore')

**Load the dataset**

In [ ]:
df=pd.read_csv('loan_prediction.csv')


In [ ]:
df

Loan_ID  Gender Married Dependents     Education Self_Employed  \
0    LP001002    Male      No          0      Graduate            No   
1    LP001003    Male     Yes          1      Graduate            No   
2    LP001005    Male     Yes          0      Graduate           Yes   
3    LP001006    Male     Yes          0  Not Graduate            No   
4    LP001008    Male      No          0      Graduate            No   
..        ...     ...     ...        ...           ...           ...   
609  LP002978  Female      No          0      Graduate            No   
610  LP002979    Male     Yes         3+      Graduate            No   
611  LP002983    Male     Yes          1      Graduate            No   
612  LP002984    Male     Yes          2      Graduate            No   
613  LP002990  Female      No          0      Graduate           Yes   

     ApplicantIncome  CoapplicantIncome  LoanAmount  Loan_Amount_Term  \
0               5849                0.0         NaN             360.0   
1               4583             1508.0       128.0             360.0   
2               3000                0.0        66.0             360.0   
3               2583             2358.0       120.0             360.0   
4               6000                0.0       141.0             360.0   
..               ...                ...         ...               ...   
609             2900                0.0        71.0             360.0   
610             4106                0.0        40.0             180.0   
611             8072              240.0       253.0             360.0   
612             7583                0.0       187.0             360.0   
613             4583                0.0       133.0             360.0   

     Credit_History Property_Area Loan_Status  
0               1.0         Urban           Y  
1               1.0         Rural           N  
2               1.0         Urban           Y  
3               1.0         Urban           Y  
4               1.0         Urban           Y  
..              ...           ...         ...  
609             1.0         Rural           Y  
610             1.0         Rural           Y  
611             1.0         Urban           Y  
612             1.0         Urban           Y  
613             0.0     Semiurban           N  

[614 rows x 13 columns]

In [ ]:
df.shape

(614, 13)

**Handle the Missing values**

In [ ]:
#checking the null values
df.isnull().sum()

Loan_ID               0
Gender               13
Married               3
Dependents           15
Education             0
Self_Employed        32
ApplicantIncome       0
CoapplicantIncome     0
LoanAmount           22
Loan_Amount_Term     14
Credit_History       50
Property_Area         0
Loan_Status           0
dtype: int64

**Treating the Null Value**

In [ ]:
numerical_features = df.select_dtypes(include = [np.number]).columns
categorical_features = df.select_dtypes(include = [np.object]).columns

In [ ]:
numerical_features

Index(['ApplicantIncome', 'CoapplicantIncome', 'LoanAmount',
       'Loan_Amount_Term', 'Credit_History'],
      dtype='object')

In [ ]:
categorical_features

Index(['Loan_ID', 'Gender', 'Married', 'Dependents', 'Education',
       'Self_Employed', 'Property_Area', 'Loan_Status'],
      dtype='object')

In [ ]:
df['Gender'] = df['Gender'].fillna(df['Gender'].mode()[0])
df['Married'] = df['Married'].fillna(df['Married'].mode()[0])
#replace + with non value 
df['Dependents'] = df['Dependents'].str.replace('+','')
df['Dependents'] = df['Dependents'].fillna(df['Dependents'].mode()[0])
df['LoanAmount'] = df['LoanAmount'].fillna(df['LoanAmount'].mode()[0])
df['Self_Employed'] = df['Self_Employed'].fillna(df['Self_Employed'].mode()[0])
df['Loan_Amount_Term'] = df['Loan_Amount_Term'].fillna(df['Loan_Amount_Term'].mode()[0])
df['Credit_History'] = df['Credit_History'].fillna(df['Credit_History'].mode()[0])


In [ ]:
#checking the null values now
df.isnull().sum()

Loan_ID              0
Gender               0
Married              0
Dependents           0
Education            0
Self_Employed        0
ApplicantIncome      0
CoapplicantIncome    0
LoanAmount           0
Loan_Amount_Term     0
Credit_History       0
Property_Area        0
Loan_Status          0
dtype: int64

**Handling Categorical Values**

In [ ]:
df.select_dtypes(include='object').columns

Index(['Loan_ID', 'Gender', 'Married', 'Dependents', 'Education',
       'Self_Employed', 'Property_Area', 'Loan_Status'],
      dtype='object')

In [ ]:
df['Gender'].unique()

array(['Male', 'Female'], dtype=object)

In [ ]:
df['Gender'].replace({'Male':1,'Female':0},inplace=True)

In [ ]:
df['Married'].unique()

array(['No', 'Yes'], dtype=object)

In [ ]:
df['Married'].replace({'Yes':1,'No':0},inplace=True)

In [ ]:
df['Dependents'].unique()

array(['0', '1', '2', '3'], dtype=object)

In [ ]:
df['Dependents'].replace({'0':0,'1':1,'2':2,'3':3},inplace=True)

In [ ]:
df['Self_Employed'].unique()

array(['No', 'Yes'], dtype=object)

In [ ]:
df['Self_Employed'].replace({'Yes':1,'No':0},inplace=True)

In [ ]:
df['Property_Area'].unique()

array(['Urban', 'Rural', 'Semiurban'], dtype=object)

In [ ]:
df['Property_Area'].replace({'Urban':2,'Rural':0,'Semiurban':1},inplace=True)

In [ ]:
df['Loan_Status'].unique()

array(['Y', 'N'], dtype=object)

In [ ]:
df['Loan_Status'].replace({'Y':1,'N':0},inplace=True)

In [ ]:
df['Education'].unique()

array(['Graduate', 'Not Graduate'], dtype=object)

In [ ]:
df['Education'].replace({'Graduate':1,'Not Graduate':0},inplace=True)

In [ ]:
df['CoapplicantIncome']=df['CoapplicantIncome'].astype("int64")
df['LoanAmount']=df['LoanAmount'].astype("int64")
df['Loan_Amount_Term']=df['Loan_Amount_Term'].astype("int64")
df['Credit_History']=df['Credit_History'].astype("int64")

In [ ]:
# dummy columns are created for the categories in Loan_ID
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
df['Loan_ID'] = le.fit_transform(df.Loan_ID)

In [ ]:
df.head()

Loan_ID  Gender  Married  Dependents  Education  Self_Employed  \
0        0       1        0           0          1              0   
1        1       1        1           1          1              0   
2        2       1        1           0          1              1   
3        3       1        1           0          0              0   
4        4       1        0           0          1              0   

   ApplicantIncome  CoapplicantIncome  LoanAmount  Loan_Amount_Term  \
0             5849                  0         120               360   
1             4583               1508         128               360   
2             3000                  0          66               360   
3             2583               2358         120               360   
4             6000                  0         141               360   

   Credit_History  Property_Area  Loan_Status  
0               1              2            1  
1               1              0            0  
2               1              2            1  
3               1              2            1  
4               1              2            1


**Balancing The Dataset**

In [ ]:
from imblearn.combine import SMOTETomek

In [ ]:
smote = SMOTETomek(0.90)

In [ ]:
#dividing the dataset into dependent and independent y and x respectively

y = df['Loan_Status']
x = df.drop(columns=['Loan_Status'],axis=1)

In [ ]:
#creating the new x and y for balance data
x_bal,y_bal = smote.fit_resample(x,y)

In [ ]:
#printing the value before and after balancing 
print(y.value_counts())
print(y_bal.value_counts())

1    422
0    192
Name: Loan_Status, dtype: int64
1    362
0    319
Name: Loan_Status, dtype: int64


**Scaling The Data**

In [ ]:
from sklearn.preprocessing import StandardScaler

In [ ]:
sc = StandardScaler()
x_bal = sc.fit_transform(x_bal)

In [ ]:
x_bal = pd.DataFrame(x_bal)

In [ ]:
x_bal.head()

0         1         2         3         4         5         6   \
0 -1.778897  0.529221 -1.143886 -0.670287  0.628881 -0.316483  0.122083   
1 -1.773100  0.529221  0.874213  0.386346  0.628881 -0.316483 -0.109593   
2 -1.767304  0.529221  0.874213 -0.670287  0.628881  3.159726 -0.399279   
3 -1.761507  0.529221  0.874213 -0.670287 -1.590125 -0.316483 -0.475589   
4 -1.755711  0.529221 -1.143886 -0.670287  0.628881 -0.316483  0.149716   

         7         8         9         10        11  
0 -0.526271 -0.285729  0.262697  0.603928  1.349767  
1 -0.029987 -0.186875  0.262697  0.603928 -1.217806  
2 -0.526271 -0.952993  0.262697  0.603928  1.349767  
3  0.249748 -0.285729  0.262697  0.603928  1.349767  
4 -0.526271 -0.026238  0.262697  0.603928  1.349767

**Splitting Data Into Train And Test**

In [ ]:
# splitting the data into training and testing set

from sklearn.model_selection import train_test_split

In [ ]:
x_train, x_test, y_train, y_test = train_test_split(x_bal, y_bal, test_size = 0.33, random_state = 42)


In [ ]:
print(x_train.shape)
print(y_train.shape)
print(x_test.shape)
print(y_test.shape)

(456, 12)
(456,)
(225, 12)
(225,)


# COMPARE THE MODEL

**Decision Tree Model**

In [ ]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report,f1_score

In [ ]:
def decisionTreeClassifier(x_train, x_test, y_train, y_test):
    dt = DecisionTreeClassifier() 
    dt.fit(x_train,y_train)
    yPred = dt.predict(x_test)
    print("****DecisionTreeClassifier****") 
    print("Confusion matrix")
    print(confusion_matrix(y_test ,yPred) ) 
    print("Classification report")
    print(classification_report (y_test, yPred))
    y_pred=dt.predict(x_test)
    y_pred1=dt.predict(x_train)
    print('Testing accuracy: ',accuracy_score(y_test,y_pred))
    print('Training accuracy: ',accuracy_score(y_train,y_pred1))

In [ ]:
decisionTreeClassifier(x_train, x_test, y_train, y_test)

****DecisionTreeClassifier****
Confusion matrix
[[72 30]
 [25 98]]
Classification report
              precision    recall  f1-score   support

           0       0.74      0.71      0.72       102
           1       0.77      0.80      0.78       123

    accuracy                           0.76       225
   macro avg       0.75      0.75      0.75       225
weighted avg       0.76      0.76      0.75       225

Testing accuracy:  0.7555555555555555
Training accuracy:  1.0


**Random Forest Model**

In [ ]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report,f1_score

In [ ]:
def randomForestClassifier(x_train, x_test, y_train, y_test):
    rf = RandomForestClassifier() 
    rf.fit(x_train,y_train)
    yPred = rf.predict(x_test)
    print("****RandomForestClassifier****") 
    print("Confusion matrix")
    print(confusion_matrix(y_test ,yPred) ) 
    print("Classification report")
    print(classification_report (y_test, yPred))
    y_pred=rf.predict(x_test)
    y_pred1=rf.predict(x_train)
    print('Testing accuracy: ',accuracy_score(y_test,y_pred))
    print('Training accuracy: ',accuracy_score(y_train,y_pred1))

In [ ]:
randomForestClassifier(x_train, x_test, y_train, y_test)

****RandomForestClassifier****
Confusion matrix
[[ 75  27]
 [ 10 113]]
Classification report
              precision    recall  f1-score   support

           0       0.88      0.74      0.80       102
           1       0.81      0.92      0.86       123

    accuracy                           0.84       225
   macro avg       0.84      0.83      0.83       225
weighted avg       0.84      0.84      0.83       225

Testing accuracy:  0.8355555555555556
Training accuracy:  1.0



**KNN Model**

In [ ]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report,f1_score

In [ ]:
def kneighborsClassifier(x_train, x_test, y_train, y_test):
    knn = KNeighborsClassifier() 
    knn.fit(x_train,y_train)
    yPred = knn.predict(x_test)
    print("****KNeighborsClassifier****") 
    print("Confusion matrix")
    print(confusion_matrix(y_test ,yPred) ) 
    print("Classification report")
    print(classification_report (y_test, yPred))
    y_pred=knn.predict(x_test)
    y_pred1=knn.predict(x_train)
    print('Testing accuracy: ',accuracy_score(y_test,y_pred))
    print('Training accuracy: ',accuracy_score(y_train,y_pred1))

In [ ]:
kneighborsClassifier(x_train, x_test, y_train, y_test)

****KNeighborsClassifier****
Confusion matrix
[[ 64  38]
 [ 12 111]]
Classification report
              precision    recall  f1-score   support

           0       0.84      0.63      0.72       102
           1       0.74      0.90      0.82       123

    accuracy                           0.78       225
   macro avg       0.79      0.76      0.77       225
weighted avg       0.79      0.78      0.77       225

Testing accuracy:  0.7777777777777778
Training accuracy:  0.8399122807017544


**Xgboost Model**

In [ ]:
from sklearn.ensemble import  GradientBoostingClassifier
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report,f1_score

In [ ]:
def xgboost(x_train, x_test, y_train, y_test):
    xg = GradientBoostingClassifier() 
    xg.fit(x_train,y_train)
    yPred = xg.predict(x_test)
    print("****Gradient BoostingClassifier****") 
    print("Confusion matrix")
    print(confusion_matrix(y_test ,yPred) ) 
    print("Classification report")
    print(classification_report (y_test, yPred))
    y_pred=xg.predict(x_test)
    y_pred1=xg.predict(x_train)
    print('Testing accuracy: ',accuracy_score(y_test,y_pred))
    print('Training accuracy: ',accuracy_score(y_train,y_pred1))

In [ ]:
xgboost(x_train, x_test, y_train, y_test)

****Gradient BoostingClassifier****
Confusion matrix
[[ 67  35]
 [  8 115]]
Classification report
              precision    recall  f1-score   support

           0       0.89      0.66      0.76       102
           1       0.77      0.93      0.84       123

    accuracy                           0.81       225
   macro avg       0.83      0.80      0.80       225
weighted avg       0.82      0.81      0.80       225

Testing accuracy:  0.8088888888888889
Training accuracy:  0.9364035087719298
